version: "3.9"
services:
  wager_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wager_service
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      - wager_mysql
    environment:
      MIGRATE_PATH: /wager_service/tools/migration/mysql/migrations
      MYSQL_URI: root:sieunhanGAobay23vong@tcp(mysql:3306)
      MYSQL_URI_PARAMS: maxAllowedPacket=0&multiStatements=true&parseTime=true&timeout=60s
      MYSQL_TEST_DB: wager_test
      MYSQL_DB: wager
  wager_mysql:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    container_name: "wager_mysql"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: sieunhanGAobay23vong
    ports:
    - "33060:33060"
    - "3306:3306"
    networks:
      backend:
        aliases:
          - mysql
networks:
  backend: